export const postsActionTypes = {
  POSTS_FETCH: "POSTS_FETCH",
  POSTS_DID_FETCH: "POSTS_DID_FETCH",
  POST_FETCH_FAIL: "POSTS_FETCH_FAIL",
};

export const categoriesActionTypes = {
  CATEGORIES_FETCH: "POST_CATEGORIES_FETCH",
  CATEGORIES_DID_FETCH: "POST_CATEGORIES_DID_FETCH",
  CATEGORIES_FETCH_FAIL: "POST_CATEGORIES_FETCH_FAIL"
};
